Used prefix 'evm_' for methods implemented main commands

diff --git a/evm b/evm
--- a/evm
+++ b/evm
@@ -13,7 +13,7 @@ readonly OS="$(uname | tr '[:upper:]' '[:lower:]')"
 readonly OS_TYPE="$(uname -m)"
 
 SCRIPT="$0"
-if [[ -h "${SCRIPT}" ]]; then
+if [[ -L "${SCRIPT}" ]]; then
   SCRIPT="$(readlink "${SCRIPT}")"
 fi
 
@@ -48,27 +48,28 @@ if [[ ! -d "${EVM_HOME}" ]]; then
   mkdir -p "${EVM_HOME}"
 fi
 
-_abort(){
-  echo "${1:-"Something went wrong! Use evm -h for help."}"; exit 1
+_abort() {
+  echo "Error: ${*:-"Something went wrong! Use evm -h for help"}" >&2
+  exit 1
 }
 
 _abort_if_too_many_arguments() {
   if [[ "$#" -gt 0 ]]; then
-    _abort "Invalid arguments: '$@'. Use evm -h for help."
+    _abort "Unknown arguments: '$*'"
   fi
 }
 
-_check_es_version() {
+_check_version() {
   local version="$1"
   if [[ -z "${version}" ]]; then
-    _abort "A version is required."
+    _abort "A version is required"
   fi
   if [[ ! "${version}" =~ ^([0-9]+\.){2}([0-9]+)(\-[a-z0-9]+)*$ ]]; then
-    _abort "Invalid version: '${version}'."
+    _abort "Invalid version: '${version}'. See https://semver.org"
   fi
 }
 
-_get_current_es_version() {
+_get_current_version() {
   local path="$(find "${EVM_HOME}" -type l -name "${ES_NAME}" -exec readlink {} +)"
   if [[ ! -z "${path}" ]]; then
     local current_version="$(basename "${path}")"
@@ -76,28 +77,29 @@ _get_current_es_version() {
   fi
 }
 
-_get_current_es_pid() {
+_get_current_pid() {
   ps -ef | grep -i [E]lasticsearch.pid | awk '{print $2}'
 }
 
-_check_curl_if_available(){
+_check_curl_if_available() {
   hash curl 2>/dev/null || _abort "The 'curl' program is required, please install 'curl' first."
 }
 
 _detect_checksum_cmd() {
   local cmd="shasum"
-  hash "${cmd}" 2>/dev/null || cmd="sha1sum"; hash "${cmd}" 2>/dev/null || _abort "sha1sum or shasum command not found."
+  hash "${cmd}" 2>/dev/null || cmd="sha1sum"
+  hash "${cmd}" 2>/dev/null || _abort "sha1sum or shasum command not found."
   echo "${cmd}"
 }
 
-_get_downloaded_file_name(){
+_get_downloaded_file_name() {
   local version="$1"
   local version_array=(${version//./ })
   local os_type="$OS_TYPE"
   local m1_platform="arm64"
-  if [[ ${version_array[0]} -ge 7 ]] ; then
+  if [[ ${version_array[0]} -ge 7 ]]; then
     if [[ "$OS_TYPE" == "$m1_platform" ]]; then
-      if [[ (${version_array[0]} -eq 7) && (${version_array[1]} -le 15) ]] ; then
+      if [[ (${version_array[0]} -eq 7) && (${version_array[1]} -le 15) ]]; then
         os_type="x86_64"
       else
         os_type="aarch64"
@@ -118,14 +120,14 @@ _download_es() {
   local curl_opts="--fail --connect-timeout 60 --max-time 3600"
   for repo in "${ES_DOWNLOAD_REPOS[@]}"; do
     local url="${repo}/${file}"
-    if curl --head --silent ${curl_opts} "${url}" > /dev/null; then
+    if curl --head --silent ${curl_opts} "${url}" >/dev/null; then
       echo "==> Downloading ${url}"
       curl -# -Lo "${output_file}" ${curl_opts} "${url}" || _abort "Could not download file ${url}"
 
       echo "==> Verifying checksum for '${output_file}'"
       local sha1_urls=("${url}.sha1" "${url}.sha1.txt")
       for sha1_url in "${sha1_urls[@]}"; do
-        if curl --head --silent ${curl_opts} "${sha1_url}" > /dev/null; then
+        if curl --head --silent ${curl_opts} "${sha1_url}" >/dev/null; then
           local sha1="$(curl -LSs ${curl_opts} "${sha1_url}" | awk '{print $1}')"
           local check_sum_cmd="$(_detect_checksum_cmd)"
           local downloaded_sha1="$("${check_sum_cmd}" "${output_file}" | awk '{print $1}')"
@@ -144,10 +146,11 @@ _download_es() {
   fi
 }
 
-install_es() {
-  local version="$1"; shift
+evm_install() {
+  local version="$1"
+  shift
   _abort_if_too_many_arguments "$@"
-  _check_es_version "${version}"
+  _check_version "${version}"
 
   if [[ -d "${ES_HOME}-${version}" ]]; then
     _abort "Elasticsearch ${version} has been already installed."
@@ -163,20 +166,21 @@ install_es() {
   # Cleanup: remove the downloaded files
   rm -rf "${install_file}" || echo "Clean failed. Could not remove the downloaded file ${install_file}!"
 
-  local current_version="$(_get_current_es_version)"
+  local current_version="$(_get_current_version)"
   if [[ -z "${current_version}" ]]; then
-       use_version "${version}"
+    use_version "${version}"
   fi
 
   echo "Elasticsearch ${version} has been installed."
 }
 
-use_version() {
-  local version="$1"; shift
+evm_use() {
+  local version="$1"
+  shift
   _abort_if_too_many_arguments "$@"
-  _check_es_version "${version}"
+  _check_version "${version}"
 
-  local use_version="${ES_HOME}-${version}"
+  local evm_use="${ES_HOME}-${version}"
   if [[ ! -d "${use_version}" ]]; then
     _abort "Elasticsearch ${version} not found."
   fi
@@ -185,34 +189,34 @@ use_version() {
   echo "Now using Elasticsearch ${version}"
 }
 
-start_es() {
-  local pid="$(_get_current_es_pid)"
+evm_start() {
+  local pid="$(_get_current_pid)"
   if [[ ! -z "${pid}" ]]; then
     _abort "Elasticsearch is already running."
   fi
 
-  local current_version="$(_get_current_es_version)"
+  local current_version="$(_get_current_version)"
   if [[ -z "${current_version}" ]]; then
     _abort "No Elasticsearch version in use."
   fi
   local cmd_opts="-d -p "${PID_FILE}""
   while getopts ":c:" option; do
     case "${option}" in
-      c)
-        local conf_path="$OPTARG"
-        if [[ ! -d "${conf_path}" ]]; then
-          _abort "Invalid config path: '${conf_path}'"
-        fi
-        case "$current_version" in
-          1.*|2.*) cmd_opts="${cmd_opts} -Des.path.conf=${conf_path}" ;;
-          *) cmd_opts="${cmd_opts} -Epath.conf=${conf_path}" ;;
-        esac
-        ;;
-      :) _abort "The option [-$OPTARG] must not be empty." ;;
-      \?) _abort "Unknown option: [-$OPTARG]. Use evm -h for help." ;;
+    c)
+      local conf_path="$OPTARG"
+      if [[ ! -d "${conf_path}" ]]; then
+        _abort "Invalid config path: '${conf_path}'"
+      fi
+      case "$current_version" in
+      1.* | 2.*) cmd_opts="${cmd_opts} -Des.path.conf=${conf_path}" ;;
+      *) cmd_opts="${cmd_opts} -Epath.conf=${conf_path}" ;;
+      esac
+      ;;
+    :) _abort "The option [-$OPTARG] must not be empty." ;;
+    \?) _abort "Unknown option: [-$OPTARG]. Use evm -h for help." ;;
     esac
   done
-  shift "$((OPTIND -1))"
+  shift "$((OPTIND - 1))"
 
   _abort_if_too_many_arguments "$@"
 
@@ -225,21 +229,22 @@ start_es() {
   ${cmd}
   while true; do
     if hash nc 2>/dev/null; then
-        if nc -z -w300ms 0.0.0.0 9300 2>/dev/null; then
-            echo "Elasticsearch $(_get_current_es_version) has been started."
-            break;
-        fi
+      if nc -z -w300ms 0.0.0.0 9300 2>/dev/null; then
+        echo "Elasticsearch $(_get_current_version) has been started."
+        break
+      fi
     else
-        if [[ -f "${PID_FILE}" ]]; then
-            echo "Elasticsearch $(_get_current_es_version) has been started."
-            break;
-        fi
+      if [[ -f "${PID_FILE}" ]]; then
+        echo "Elasticsearch $(_get_current_version) has been started."
+        break
+      fi
     fi
   done
 }
 
-stop_es() {
-  local pid="$(_get_current_es_pid)"
+evm_stop() {
+  _abort_if_too_many_arguments "$@"
+  local pid="$(_get_current_pid)"
   if [[ -z "${pid}" ]]; then
     _abort "Elasticsearch is not running."
   fi
@@ -249,27 +254,28 @@ stop_es() {
   echo "Elasticsearch has been stopped."
 }
 
-
-print_es_running_status() {
-  local pid="$(_get_current_es_pid)"
+evm_status() {
+  _abort_if_too_many_arguments "$@"
+  local pid="$(_get_current_pid)"
   if [[ ! -z "${pid}" ]]; then
-    echo "Elasticsearch $(_get_current_es_version) is running."
+    echo "Elasticsearch $(_get_current_version) is running."
   else
     echo "Elasticsearch is not running."
   fi
 }
 
-remove_es() {
-  local version="$1"; shift
+evm_remove() {
+  local version="$1"
+  shift
   _abort_if_too_many_arguments "$@"
-  _check_es_version "${version}"
+  _check_version "${version}"
 
   local removed_version_folder="${ES_HOME}-${version}"
   if [[ ! -d "${removed_version_folder}" ]]; then
     _abort "Elasticsearch ${version} not found."
   fi
 
-  local current_version="$(_get_current_es_version)"
+  local current_version="$(_get_current_version)"
   if [[ "${version}" = "${current_version}" ]]; then
     _abort "Could not remove Elasticsearch ${version}, it is in use."
   fi
@@ -278,8 +284,8 @@ remove_es() {
   echo "Elasticsearch ${version} has been removed."
 }
 
-manage_es_plugin() {
-  local current_version="$(_get_current_es_version)"
+evm_plugin() {
+  local current_version="$(_get_current_version)"
   if [[ -z "${current_version}" ]]; then
     _abort "No Elasticsearch version in use. Use evm -h for help."
   fi
@@ -288,50 +294,54 @@ manage_es_plugin() {
   local install_opt="${INSTALL_CMD}"
   local remove_opt="${REMOVE_CMD}"
   case "${current_version}" in
-    1.*)
-      cmd="${ES_1X_PLUGIN_CMD}"
-      list_opt="--${list_opt}"
-      install_opt="--${install_opt}"
-      remove_opt="--${remove_opt}"
-      ;;
-    2.*) cmd="${ES_1X_PLUGIN_CMD}" ;;
-    *) cmd="${ES_PLUGIN_CMD}" ;;
+  1.*)
+    cmd="${ES_1X_PLUGIN_CMD}"
+    list_opt="--${list_opt}"
+    install_opt="--${install_opt}"
+    remove_opt="--${remove_opt}"
+    ;;
+  2.*) cmd="${ES_1X_PLUGIN_CMD}" ;;
+  *) cmd="${ES_PLUGIN_CMD}" ;;
   esac
   if [ ! -x "$cmd" ]; then
     _abort "The Elasticsearch plugin command not found or unexecutable."
   fi
 
-  local plugin_sub_cmd="$1"; shift
+  local plugin_sub_cmd="$1"
+  shift
   case "$plugin_sub_cmd" in
-    ${LIST_CMD})
-      _abort_if_too_many_arguments "$@"
-      cmd="$cmd $list_opt"
-      ;;
-    ${INSTALL_CMD})
-      local plugin="$1"; shift
-      _abort_if_too_many_arguments "$@"
-      if [[ -z "${plugin}" ]]; then
-        _abort "A plugin is required."
-      fi
-      cmd="$cmd $install_opt ${plugin}"
-      ;;
-    ${REMOVE_CMD})
-      local plugin="$1"; shift
-      _abort_if_too_many_arguments "$@"
-      if [[ -z "${plugin}" ]]; then
-        _abort "A plugin is required."
-      fi
-      cmd="$cmd $remove_opt ${plugin}"
-      ;;
-    *)
-      _abort "Unknown command: '${plugin_sub_cmd}'. Use evm -h for help."
-      ;;
+  ${LIST_CMD})
+    _abort_if_too_many_arguments "$@"
+    cmd="$cmd $list_opt"
+    ;;
+  ${INSTALL_CMD})
+    local plugin="$1"
+    shift
+    _abort_if_too_many_arguments "$@"
+    if [[ -z "${plugin}" ]]; then
+      _abort "A plugin is required."
+    fi
+    cmd="$cmd $install_opt ${plugin}"
+    ;;
+  ${REMOVE_CMD})
+    local plugin="$1"
+    shift
+    _abort_if_too_many_arguments "$@"
+    if [[ -z "${plugin}" ]]; then
+      _abort "A plugin is required."
+    fi
+    cmd="$cmd $remove_opt ${plugin}"
+    ;;
+  *)
+    _abort "Unknown command: '${plugin_sub_cmd}'. Use evm -h for help."
+    ;;
   esac
   ${cmd}
 }
 
-list_es_versions() {
-  local current_version="$(_get_current_es_version)"
+evm_list() {
+  _abort_if_too_many_arguments "$@"
+  local current_version="$(_get_current_version)"
   for e in $(find "${EVM_HOME}" -maxdepth 1 -mindepth 1 -type d -name "${ES_NAME}-*" | sort -nr); do
     local version="$(basename "${e}")"
     version="$(echo "${version#*-}")"
@@ -343,17 +353,18 @@ list_es_versions() {
   done
 }
 
-print_evm_version(){
+evm_V() {
   echo "${EVM_NAME} ${EVM_VERSION}"
 }
 
-print_current_es_version() {
-  _get_current_es_version
+evm_version() {
+  _abort_if_too_many_arguments "$@"
+  _get_current_version
 }
 
-print_es_path(){
-  local version="${1:-$(_get_current_es_version)}"
-  _check_es_version "${version}"
+evm_which() {
+  local version="${1:-$(_get_current_version)}"
+  _check_version "${version}"
 
   local path="$ES_HOME-$version"
   if [[ -d "${path}" ]]; then
@@ -363,7 +374,7 @@ print_es_path(){
   fi
 }
 
-print_usage() {
+evm_help() {
   cat <<'EOF'
 
 Elasticsearch Version Manager
@@ -401,37 +412,32 @@ EOF
 main() {
   while getopts ":hV" opt; do
     case "${opt}" in
-      h) print_usage; exit 0 ;;
-      V) print_evm_version; exit 0 ;;
-      \?) _abort "Unknown option: -${OPTARG}. Use evm -h for help." ;;
+    h)
+      evm_help
+      exit 0
+      ;;
+    V)
+      evm_V
+      exit 0
+      ;;
+    \?) _abort "Unknown option: -${OPTARG}. Use evm -h for help." ;;
     esac
   done
-  shift "$((OPTIND -1))"
-  sub_cmd="$1"; shift
-  case "${sub_cmd}" in
-    ${INSTALL_CMD}) install_es "$@" ;;
-    ${USE_CMD}) use_version "$@" ;;
-    ${START_CMD}) start_es "$@" ;;
-    ${STOP_CMD})
-      _abort_if_too_many_arguments "$@"
-      stop_es
-      ;;
-    ${STATUS_CMD})
-      _abort_if_too_many_arguments "$@"
-      print_es_running_status
-      ;;
-    ${REMOVE_CMD}) remove_es "$@" ;;
-    ${PLUGIN_CMD}) manage_es_plugin "$@" ;;
-    ${WHICH_CMD}) print_es_path "$@" ;;
-    ${LIST_CMD})
-      _abort_if_too_many_arguments "$@"
-      list_es_versions
-      ;;
-    ${VERSION_CMD})
-      _abort_if_too_many_arguments "$@"
-      print_current_es_version
-      ;;
-    *) print_usage ;;
+  shift "$((OPTIND - 1))"
+  local subcmd="$1"
+  shift
+  case "${subcmd}" in
+  "${INSTALL_CMD}") evm_install "$@" ;;
+  "${USE_CMD}") evm_use "$@" ;;
+  "${START_CMD}") evm_start "$@" ;;
+  "${STOP_CMD}") evm_stop "$@" ;;
+  "${STATUS_CMD}") evm_status "$@" ;;
+  "${REMOVE_CMD}") evm_remove "$@" ;;
+  "${PLUGIN_CMD}") evm_plugin "$@" ;;
+  "${WHICH_CMD}") evm_which "$@" ;;
+  "${LIST_CMD}") evm_list "$@" ;;
+  "${VERSION_CMD}") evm_version "$@";;
+  *) evm_help ;;
   esac
 }
 
