refactoring, use getopts to parse options

diff --git a/evm b/evm
--- a/evm
+++ b/evm
@@ -7,201 +7,231 @@
 # Version: 0.1.3
 # Author: Duy Do (duydo)
 # Contributors: Quang Nguyen (xluffy), Nham Le (nhamlh)
-
 EVM_VERSION="0.1.3"
 
 SCRIPT="$0"
 # SCRIPT may be an arbitrarily deep series of symlinks, lookup the concrete path.
-if [[ -h "$SCRIPT" ]]; then
-  SCRIPT=$(readlink "$SCRIPT")
+if [[ -h "${SCRIPT}" ]]; then
+  SCRIPT=$(readlink "${SCRIPT}")
 fi
 
-EVM_NAME=$(basename "$SCRIPT")
-EVM_HOME=${EVM_HOME:-"$HOME/.$EVM_NAME"}
+EVM_NAME=$(basename "${SCRIPT}")
+EVM_HOME=${EVM_HOME:-"${HOME}/.${EVM_NAME}"}
 
 ES="elasticsearch"
-ES_HOME="$EVM_HOME/$ES"
+ES_HOME="${EVM_HOME}/${ES}"
+ES_CMD="${ES_HOME}/bin/${ES}"
+ES_PLUGIN_CMD="${ES_HOME}/bin/${ES}-plugin"
+ES_1X_PLUGIN_CMD="${ES_HOME}/bin/plugin"
 
+# Sub commands
+START_CMD='start'
+INSTALL_CMD='install'
+REMOVE_CMD='remove'
+LIST_CMD='list'
+USE_CMD='use'
+PLUGIN_CMD='plugin'
+VERSION_CMD='version'
+WHICH_CMD='which'
+
+# Elasticsearch download repos
 ES_1X_DOWNLOAD_REPO="https://download.elastic.co/elasticsearch/elasticsearch"
 ES_2X_DOWNLOAD_REPO="https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch"
 ES_5X_DOWNLOAD_REPO="https://artifacts.elastic.co/downloads/elasticsearch"
 ES_DOWNLOAD_EXT="tar.gz"
 
 # First use?
-if [ ! -d "$EVM_HOME" ]; then
-  mkdir -p "$EVM_HOME";
+if [ ! -d "${EVM_HOME}" ]; then
+  mkdir -p "${EVM_HOME}";
 fi
 
 
 abort(){
-  echo "${1:-"Something went wrong. Abort!"}"
-  exit 3
+  echo "${1:-"Something went wrong. Use evm -h for help."}"; exit 1
 }
 
-_check_es_version() {
-  version="$1"
-  if [[ -z "$version" ]]; then
+_check_version() {
+  local version="$1"
+  if [[ -z "${version}" ]]; then
     abort "A version is required."
-  fi
-
-  if [[ ! "$version" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
-    abort "Invalid version '$version'!!!"
+  elif [[ ! "${version}" =~ ^([0-9]+\.){2}(\*|[0-9]+)$ ]]; then
+    abort "Invalid version: '${version}'."
   fi
 }
 
-_get_es_download_link() {
-  version="$1"
-  download_file="$ES-$version.$ES_DOWNLOAD_EXT"
-  case "$version" in
-    5.*)
-      download_link="$ES_5X_DOWNLOAD_REPO/$download_file"
-      ;;
+_get_download_link() {
+  local version="$1"
+  local download_file="${ES}-${version}.${ES_DOWNLOAD_EXT}"
+  case "${version}" in
     2.*)
-      download_link="$ES_2X_DOWNLOAD_REPO/$version/$download_file"
+      download_link="${ES_2X_DOWNLOAD_REPO}/${version}/${download_file}"
       ;;
     1.*)
-      download_link="$ES_1X_DOWNLOAD_REPO/$download_file"
+      download_link="${ES_1X_DOWNLOAD_REPO}/${download_file}"
+      ;;
+    *)
+      download_link="${ES_5X_DOWNLOAD_REPO}/${download_file}"
       ;;
   esac
   # Check if the download link exists
-  if [[ ! -z "$download_link" ]]; then
-      _=$(wget --spider --tries 1 "$download_link" 2>&1)
+  if [[ ! -z "${download_link}" ]]; then
+      _=$(wget --spider --tries 1 "${download_link}" 2>&1)
       if [ $? -eq 0 ]; then
-        echo "$download_link"
+        echo "${download_link}"
       fi
   fi
 }
 
-get_current_es_version() {
-  current_version="$(basename "$(find "$EVM_HOME" -type l -name "$ES" -exec readlink {} +)")"
-  echo "$current_version" | cut -d "-" -f 2
+get_current_version() {
+  local current_version="$(basename "$(find "${EVM_HOME}" -type l -name "${ES}" -exec readlink {} +)")"
+  echo "${current_version}" | cut -d "-" -f 2
 }
 
-install_es_version() {
-  version="$1"
-  _check_es_version "$version"
+install_version() {
 
-  if [[ -d "$ES_HOME-$version" ]]; then
-    abort "Elasticsearch $version has been already installed."
+  local version="$1"
+  _check_version "${version}"
+
+  if [[ -d "${ES_HOME}-${version}" ]]; then
+    abort "Elasticsearch ${version} has been already installed."
   fi
 
-  download_link="$(_get_es_download_link "$version")"
-  if [[ -z "$download_link" ]]; then
-    abort "Elasticsearch $version not found."
+  local download_link="$(_get_download_link "${version}")"
+  if [[ -z "${download_link}" ]]; then
+    abort "Elasticsearch ${version} not found."
   fi
 
-  echo "-> Downloading Elasticsearch $version from elastic.co"
-  echo "Retrieving $download_link"
-  output_file="$EVM_HOME/$ES-$version.$ES_DOWNLOAD_EXT"
-  wget -nc "$download_link" -O "$output_file"
+  echo "-> Downloading Elasticsearch ${version} from elastic.co"
+  echo "Retrieving ${download_link}"
+  local output_file="${EVM_HOME}/${ES}-${version}.${ES_DOWNLOAD_EXT}"
+  wget -nc "${download_link}" -O "${output_file}"
 
   # TODO: Verify downloaded file's checksum before installing (suggested by @xluffy)
 
-  echo "Installing $output_file"
-  tar -xzf "$output_file" -C "$EVM_HOME/"
-  echo "-> Installed Elasticsearch $version"
+  echo "Installing ${output_file}"
+  tar -xzf "${output_file}" -C "${EVM_HOME}/"
 
   # Use this version if no other version in use
-  current_version=$(get_current_es_version)
-  if [ -z "$current_version" ]; then
-    use_es_version "$version"
+  local current_version=$(get_current_version)
+  if [ -z "${current_version}" ]; then
+    use_version "${version}"
   fi
 
-  # Remove the download file
-  rm -rf "$output_file"
+  # Remove the downloaded file
+  if rm -rf "${output_file}"; then
+    echo "Removed ${output_file}"
+  fi
+
+  echo "-> Installed Elasticsearch ${version}"
 }
 
-use_es_version() {
-  version="$1"
-  _check_es_version "$version"
-
-  use_version="$ES_HOME-$version"
-  if [[ ! -d "$use_version" ]]; then
-    abort "Elasticsearch $version not found. Using 'evm list' to see available versions."
+use_version() {
+  local version="$1"
+  _check_version "${version}"
+  local use_version="${ES_HOME}-${version}"
+  if [[ ! -d "${use_version}" ]]; then
+    abort "Elasticsearch ${version} not found. Use 'evm list' to see available versions."
   fi
-  ln -sfn "$use_version" "$ES_HOME"
-  echo "-> Now using Elasticsearch $version"
-}
-
-start_current_es_version() {
-  cmd="$ES_HOME/bin/elasticsearch"
-  if [[ ! -x "$cmd" ]]; then
-    abort "No Elasticsearch version in use."
-  fi
-  option_config_path="$1"
-  if [[ "$option_config_path" = "--config-path" ]]; then
-    config_path="$2"
-    if [[ ! -d "$config_path" ]]; then
-      abort "config path '$config_path' does not exist or cannot access."
-    fi
-    cmd="$cmd -Epath.conf=$config_path"
-  fi
-  ${cmd}
-}
-
-remove_es_version() {
-  version="$1"
-  _check_es_version "$version"
-
-  removed_version="$ES-$version"
-  if [[ ! -d "$EVM_HOME/$removed_version" ]]; then
-    abort "Elasticsearch $version has been already installed."
-  fi
-
-  current_version="$(get_current_es_version)"
-  if [[ "$version" = "$current_version" ]]; then
-    abort "Elasticsearch $version is in use."
-  fi
-
-  if rm -rf "$EVM_HOME/$removed_version"; then
-    echo "-> Elasticsearch $version has been removed."
+  if ln -sfn "${use_version}" "${ES_HOME}"; then
+    echo "-> Now using Elasticsearch ${version}"
   else
-    abort "Couldnot remove the version $version"
+    abort
   fi
 }
 
-manage_es_plugin() {
-  if [[ ! -f "$ES_HOME/bin/elasticsearch" ]]; then
-    abort "No Elasticsearch version found."
+start_current_version() {
+	local cmd="${ES_CMD}"
+  if [[ ! -x "${cmd}" ]]; then
+    abort "The command ${cmd} is not executable, no Elasticsearch version in use."
   fi
-  # 5.x?
-  cmd="$ES_HOME/bin/elasticsearch-plugin"
-  option_list="list"
-  option_install="install"
-  option_remove="remove"
-  if [[ ! -f "$cmd" ]]; then
-    # No? Try 1.x or 2.x...
-    cmd="$ES_HOME/bin/plugin"
-    option_list="--$option_list"
-    option_install="--$option_install"
-    option_remove="--$option_remove"
-    if [[ ! -f "$cmd" ]]; then
-      # No?
-      abort "The plugin command not found."
-    fi
-  fi
-  option="$1"
-  if [[ "x$option" == "x" ]]; then
-    echo "-> Retrieving installed plugins"
-    cmd="$cmd $option_list"
-  else
-    plugin="$2"
-    case "$option" in
-      install)
-        cmd="$cmd $option_install $plugin"
-        ;;
-      remove)
-        cmd="$cmd $option_remove $plugin"
-        ;;
-      *)
-      abort "Unknown plugin option. Use evm -h for help."
+	while getopts ":c:" option; do
+    case "${option}" in
+      c)
+        local config_path="$OPTARG"
+        if [[ ! -d "${config_path}" ]]; then
+          abort "Invalid config path: '${config_path}'"
+        fi
+        local current_version="$(get_current_version)"
+				case "$current_version" in
+				  1.*|2.*) cmd="${cmd} -Des.path.conf=${config_path}" ;;
+          *) cmd="${cmd} -Epath.conf=${config_path}" ;;
+        esac
     esac
+	done
+	${cmd}
+}
+
+remove_version() {
+  local version="$1"
+  _check_version "${version}"
+
+  local removed_version_folder="${ES}-${version}"
+  if [[ ! -d "${EVM_HOME}/${removed_version_folder}" ]]; then
+    abort "Elasticsearch ${version} not found."
   fi
+
+  local current_version="$(get_current_version)"
+  if [[ "${version}" = "${current_version}" ]]; then
+    abort "Elasticsearch ${version} is in use."
+  fi
+
+  if rm -rf "${EVM_HOME}/${removed_version_folder}"; then
+    abort "Could not remove the version ${version}."
+  else
+    echo "-> Elasticsearch ${version} has been removed"
+  fi
+}
+
+manage_plugin() {
+
+  list_option="list"
+  install_option="install"
+  remove_option="remove"
+
+  local current_version="$(get_current_version)"
+  case "${current_version}" in
+    '')
+      abort "No Elasticsearch version in use. Use evm -h for help."
+      ;;
+    1.*)
+      cmd="${ES_HOME}/bin/plugin"
+      list_option="--list"
+      install_option="--install"
+      remove_option="--remove"
+      ;;
+    2.*)
+      cmd="${ES_HOME}/bin/plugin"
+      ;;
+    *)
+      cmd="${ES_HOME}/bin/elasticsearch-plugin"
+      ;;
+  esac
+
+  if [ ! -x "$cmd" ]; then
+    abort "The Elasticsearch plugin command not found or unexecutable."
+  fi
+
+  plugin_sub_cmd="$1"
+  shift
+  case "$plugin_sub_cmd" in
+    list)
+      cmd="$cmd $list_option"
+      ;;
+    install)
+      cmd="$cmd $install_option $@"
+      ;;
+    remove)
+      cmd="$cmd $remove_option $@"
+      ;;
+    *)
+      abort "The command 'plugin' requires a valid argument. Use evm -h for help."
+    ;;
+  esac
   ${cmd}
 }
 
-list_es_versions() {
-  current_version=$(get_current_es_version)
+list_versions() {
+  local current_version=$(get_current_version)
   for e in $(find "$EVM_HOME" -maxdepth 1 -mindepth 1 -type d -name "$ES-*" | sort -nr); do
     version="$(basename "$e")"
     version="$(echo $version | cut -d "-" -f 2)"
@@ -213,78 +243,78 @@ list_es_versions() {
   done
 }
 
-usage() {
+print_usage() {
   cat <<'EOF'
 
 Elasticsearch Version Manager
 
 Usage:
- evm list                                           List all versions of Elasticsearch have been installed
+ evm -h                                             Print help information
+ evm -V                                             Print version information
+ evm list                                           List all installed Elasticsearch versions
+ evm version                                        Print the current activated Elasticsearch version
  evm install <version>                              Install a specific Elasticsearch version
- evm remove <version>                               Remove a specific Elasticsearch version
  evm use <version>                                  Use a specific Elasticsearch version
- evm which                                          Display the current Elasticsearch version
- evm plugin [<install|remove> <plugin>]             List, install or remove an Elasticsearch plugin
- evm start [--config-path </path/to/config/dir>]    Start Elasticsearch node with/without a specific config directory
- evm -h or --help                                   Display usage information
- evm -V or --version                                Display version information
+ evm remove <version>                               Remove a specific Elasticsearch version if available
+ evm which [<version>]                              Print path to installed Elasticsearch version
+ evm plugin list                                    List all installed Elasticsearch plugins
+ evm plugin <install|remove> <plugin>               Install or remove an Elasticsearch plugin
+ evm start [-c </path/to/config/dir>]               Start Elasticsearch with/without a specific config directory
 
 Example:
  evm install 5.3.1                                  Install Elasticsearch 5.3.1
  evm use 5.3.1                                      Use Elasticsearch 5.3.1
  evm start                                          Start Elasticsearch node with the default config directory
- evm start --config-path /etc/elasticsearch         Start Elasticsearch node with /etc/elasticsearch config directory
+ evm start -c /etc/elasticsearch                    Start Elasticsearch node with /etc/elasticsearch config directory
  evm plugin install x-pack                          Install the x-pack plugin
  evm plugin remove x-pack                           Remove the x-pack plugin
 
-Note: To remove, delete or uninstall evm - just remove the EVM_HOME folder (usually ~/.evm)
+Note: To remove evm - just remove the EVM_HOME folder (usually ~/.evm)
 
 EOF
 }
 
-print_version(){
+print_evm_version(){
   echo "$EVM_NAME $EVM_VERSION"
 }
 
-print_current_es_version() {
-  echo "$(get_current_es_version)"
+print_current_version() {
+  echo "$(get_current_version)"
+}
+
+print_version_path(){
+  local version="${1:-$(get_current_version)}"
+  local path="$EVM_HOME/$ES-$version"
+  if [[ -d "${path}" ]]; then
+    echo "${path}"
+  else
+    echo "Elasticsearch version not found."
+  fi
 }
 
 main() {
-  cmd="$1"
-  args="${@:2}"
-  case "$cmd" in
-    install)
-      install_es_version "$args"
-      ;;
-    use)
-      use_es_version "$args"
-      ;;
-    start)
-      start_current_es_version "$args"
-      ;;
-    remove)
-      remove_es_version "$args"
-      ;;
-    plugin)
-      manage_es_plugin "$args"
-      ;;
-    list)
-      list_es_versions
-      ;;
-    which)
-      print_current_es_version
-      ;;
-    -V|--version)
-      print_version
-      ;;
-    -h|--help)
-      usage
-      ;;
-    *)
-      usage
-      ;;
+  while getopts ":hV" opt; do
+    case "${opt}" in
+      h) print_usage; exit 0 ;;
+      V) print_evm_version; exit 0 ;;
+      \?) abort "Unknown option: -${OPTARG}. Use evm -h for help." ;;
+    esac
+  done
+  shift "$((OPTIND -1))"
+
+  sub_cmd="$1"; shift
+  case "${sub_cmd}" in
+    ${INSTALL_CMD}) install_version "$@" ;;
+    ${USE_CMD}) use_version "$@" ;;
+    ${START_CMD}) start_current_version "$@" ;;
+    ${REMOVE_CMD}) remove_version "$@" ;;
+    ${PLUGIN_CMD}) manage_plugin "$@" ;;
+    ${WHICH_CMD}) print_version_path "$@" ;;
+    ${LIST_CMD}) list_versions ;;
+    ${VERSION_CMD}) print_current_version ;;
+    *) abort "Invalid command: '${sub_cmd}'. Use evm -h for help." ;;
   esac
+
 }
 
 main "$@"
