replace wget with curl, refactoring

diff --git a/evm b/evm
--- a/evm
+++ b/evm
@@ -10,12 +10,10 @@
 
 readonly EVM_VERSION="0.1.5"
 
-readonly OS="$(uname | tr '[:upper:]' '[:lower:]'))"
+readonly OS="$(uname | tr '[:upper:]' '[:lower:]')"
 readonly OS_TYPE="$(uname -m)"
 
-
 SCRIPT="$0"
-# SCRIPT may be an arbitrarily deep series of symlinks, lookup the concrete path.
 if [[ -h "${SCRIPT}" ]]; then
   SCRIPT="$(readlink "${SCRIPT}")"
 fi
@@ -41,18 +39,13 @@ readonly PLUGIN_CMD='plugin'
 readonly VERSION_CMD='version'
 readonly WHICH_CMD='which'
 
-# Elasticsearch download repos
-readonly ES_1X_DOWNLOAD_REPO="https://download.elastic.co/elasticsearch/elasticsearch"
-readonly ES_2X_DOWNLOAD_REPO="https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch"
-readonly ES_5X_DOWNLOAD_REPO="https://artifacts.elastic.co/downloads/elasticsearch"
-readonly KIBANA_5X_DOWNLOAD_REPO="https://artifacts.elastic.co/downloads/kibana"
-
+readonly ES_DOWNLOAD_REPOS=("https://artifacts.elastic.co/downloads/${ES_NAME}" "https://download.elastic.co/${ES_NAME}/${ES_NAME}")
 readonly DOWNLOAD_EXT="tar.gz"
 readonly DOWNLOAD_CHECKSUM_EXT="sha1"
 
 # First use?
 if [[ ! -d "${EVM_HOME}" ]]; then
-  mkdir -p "${EVM_HOME}";
+  mkdir -p "${EVM_HOME}"
 fi
 
 _abort(){
@@ -60,8 +53,8 @@ _abort(){
 }
 
 _abort_if_too_many_arguments() {
-  if [[ ! -z "$@" ]]; then
-    _abort "Too many arguments. Use evm -h for help."
+  if [[ "$#" -gt 0 ]]; then
+    _abort "Invalid arguments: '$@'. Use evm -h for help."
   fi
 }
 
@@ -69,121 +62,99 @@ _check_es_version() {
   local version="$1"
   if [[ -z "${version}" ]]; then
     _abort "A version is required."
-  elif [[ ! "${version}" =~ ^([0-9]+\.){2}(\*|[0-9]+)$ ]]; then
+  fi
+  if [[ ! "${version}" =~ ^([0-9]+\.){2}(\*|[0-9]+)$ ]]; then
     _abort "Invalid version: '${version}'."
   fi
 }
 
-_get_es_download_link() {
-  local version="$1"
-  local download_file="${ES_NAME}-${version}.${DOWNLOAD_EXT}"
-  case "${version}" in
-    2.*)
-      download_link="${ES_2X_DOWNLOAD_REPO}/${version}/${download_file}"
-      ;;
-    1.*)
-      download_link="${ES_1X_DOWNLOAD_REPO}/${download_file}"
-      ;;
-    *)
-      download_link="${ES_5X_DOWNLOAD_REPO}/${download_file}"
-      ;;
-  esac
-  # Check if the download link exists
-  if [[ ! -z "${download_link}" ]]; then
-      if wget --spider --tries 1 --timeout 300 "${download_link}" 2>/dev/null; then
-        echo "${download_link}"
-      fi
+_get_current_es_version() {
+  local path="$(find "${EVM_HOME}" -type l -name "${ES_NAME}" -exec readlink {} +)"
+  if [[ ! -z "${path}" ]]; then
+    local current_version="$(basename "${path}")"
+    echo "${current_version}" | cut -d "-" -f 2
   fi
 }
 
-_get_current_es_version() {
-  local current_version="$(basename "$(find "${EVM_HOME}" -type l -name "${ES_NAME}" -exec readlink {} +)")"
-  echo "${current_version}" | cut -d "-" -f 2
-}
-
-_get_checksum_cmd() {
-  local cmd="sha1sum"
-  hash "${cmd}" 2>/dev/null || cmd="shasum"; hash "${cmd}" 2>/dev/null || _abort "sha1sum or shasum command not found."
-  echo "${cmd}"
-}
-
 _get_current_es_pid() {
-    echo "$(ps -ef | grep -i [E]lasticsearch | awk '{print $1}')"
+  ps -ef | grep -i [E]lasticsearch | awk '{print $2}'
 }
 
 _wait_for_es_started_completely() {
-  local pid=$(_get_current_es_pid)
+  #TODO: Find a better way to handle this, use nc to check for now.
+  local pid="$(_get_current_es_pid)"
   while [ "${pid}" ]; do
-     if nc -z 0.0.0.0 9200 > /dev/null 2>&1; then
-       local current_version=$(_get_current_es_version)
-       echo "Elasticsearch ${current_version} has been started."
-       break
-     fi
+    if nc -z 0.0.0.0 9300 > /dev/null 2>&1; then
+      echo "Elasticsearch $(_get_current_es_version) has been started."
+      break
+    fi
   done
 }
 
-_download_checksum() {
-  local checksum_link="$1"
-  local checksum_file="$2"
-  wget -c "${checksum_link}" -O "${checksum_file}" || checksum_link="${checksum_link}.txt"; wget -c "${checksum_link}" -O "${checksum_file}"
-  local checksum_value=$(<"${checksum_file}")
-  echo "${checksum_value}" | awk '{print $1}' # compatible with 1.x checksum value
+_check_curl_if_available(){
+  hash curl 2>/dev/null || _abort "The 'curl' program is required, please install 'curl' first."
 }
 
-_check_network_connection(){
-  nc -z 8.8.8.8 53 > /dev/null 2>&1 || _abort "Your internet connection has been broken, please check."
+_detect_checksum_cmd() {
+  local cmd="shasum"
+  hash "${cmd}" 2>/dev/null || cmd="sha1sum"; hash "${cmd}" 2>/dev/null || _abort "sha1sum or shasum command not found."
+  echo "${cmd}"
+}
+_download_es() {
+  _check_curl_if_available
+  local version="$1"
+  local file="${ES_NAME}-${version}.${DOWNLOAD_EXT}"
+  local output_file="${EVM_HOME}/${file}"
+  echo "==> Downloading Elasticsearch ${version} from elastic.co"
+  local curl_opts="--fail --connect-timeout 60 --max-time 3600"
+  for repo in "${ES_DOWNLOAD_REPOS[@]}"; do
+    local url="${repo}/${file}"
+    if curl --head --silent ${curl_opts} "${url}" > /dev/null; then
+      echo "==> Downloading ${url}"
+      curl -# -Lo "${output_file}" ${curl_opts} "${url}" || _abort "Could not download file ${url}"
+
+      echo "==> Verifying checksum for '${output_file}'"
+      local sha1_urls=("${url}.sha1" "${url}.sha1.txt")
+      for sha1_url in "${sha1_urls[@]}"; do
+        if curl --head --silent ${curl_opts} "${sha1_url}" > /dev/null; then
+          local sha1="$(curl -LSs ${curl_opts} "${sha1_url}" | awk '{print $1}')"
+          local check_sum_cmd="$(_detect_checksum_cmd)"
+          local downloaded_sha1="$("${check_sum_cmd}" "${output_file}" | awk '{print $1}')"
+          if [[ ! "${downloaded_sha1}" == "${sha1}" ]]; then
+            _abort "Checksum mismatched for '${output_file}'. Expected: ${sha1}, Received: ${downloaded_sha1}"
+          fi
+          break
+        fi
+      done
+      break
+    fi
+  done
 }
 
 install_es() {
   local version="$1"; shift
   _abort_if_too_many_arguments "$@"
   _check_es_version "${version}"
-
   if [[ -d "${ES_HOME}-${version}" ]]; then
     _abort "Elasticsearch ${version} has been already installed."
   fi
 
-  _check_network_connection
-
-
-  local download_link="$(_get_es_download_link "${version}")"
-  if [[ -z "${download_link}" ]]; then
-    _abort "Version ${version} not found."
-  fi
-
-  echo "-> Downloading Elasticsearch ${version} from elastic.co"
-
-  echo "Retrieving ${download_link}"
+  _download_es "${version}"
   local install_file="${EVM_HOME}/${ES_NAME}-${version}.${DOWNLOAD_EXT}"
-  wget -c "${download_link}" -O "${install_file}" || _abort "Could not download ${install_file}."
+  if [[ ! -f "${install_file}" ]]; then
+    _abort "File '${install_file}' not found."
+  fi
+  echo "==> Installing ${install_file} into ${EVM_HOME}/$ES_NAME-${version}"
+  tar -xzf "${install_file}" -C "${EVM_HOME}/" || _abort "Could not extract the ${install_file}, please try to install again."
+  # Cleanup: remove the downloaded files
+  rm -rf "${install_file}" || echo "Clean failed. Could not remove the downloaded file ${install_file}!"
 
-  local checksum_link="${download_link}.${DOWNLOAD_CHECKSUM_EXT}"
-  local checksum_file="${install_file}.${DOWNLOAD_CHECKSUM_EXT}"
-
-  echo "Retrieving ${checksum_link}"
-  local checksum_value=$(_download_checksum "${checksum_link}" "${checksum_file}")
-
-  echo "Verifying ${install_file}'s checksum"
-  local checksum_cmd="$(_get_checksum_cmd)"
-  local checksum_value_to_check=$("${checksum_cmd}" "${install_file}" | awk '{print $1}')
-
-  if [[ "${checksum_value}" = "${checksum_value_to_check}" ]]; then
-    echo "Installing ${install_file} into ${EVM_HOME}"
-    tar -xzf "${install_file}" -C "${EVM_HOME}/" || _abort "Could not extract the ${install_file}, please try to install again."
-
-    # Cleanup: remove the downloaded files
-    rm -rf "${install_file}" || echo "Clean failed. Could not remove the downloaded file ${install_file}!"
-    rm -rf "${checksum_file}" || echo "Clean failed. Could not remove the downloaded file ${checksum_file}!"
-
-    echo "-> Installed Elasticsearch ${version}"
-
-     # Use this version if no other version in use
-    local current_version=$(_get_current_es_version)
-    if [[ -z "${current_version}" ]]; then
+  local current_version=$(_get_current_es_version)
+  if [[ -z "${current_version}" ]]; then
        use_version "${version}"
-    fi
   fi
 
+  echo "Elasticsearch ${version} has been installed."
 }
 
 use_version() {
@@ -197,7 +168,7 @@ use_version() {
   fi
 
   ln -sfn "${use_version}" "${ES_HOME}" || _abort "Could not create symbolic link ${ES_HOME} => ${use_version}"
-  echo "-> Now using Elasticsearch ${version}"
+  echo "Now using Elasticsearch ${version}"
 }
 
 start_es() {
@@ -220,12 +191,8 @@ start_es() {
           _abort "Invalid config path: '${conf_path}'"
         fi
         case "$current_version" in
-          1.*|2.*)
-            cmd_opts="${cmd_opts} -Des.path.conf=${conf_path}"
-            ;;
-          *)
-            cmd_opts="${cmd_opts} -Epath.conf=${conf_path}"
-            ;;
+          1.*|2.*) cmd_opts="${cmd_opts} -Des.path.conf=${conf_path}" ;;
+          *) cmd_opts="${cmd_opts} -Epath.conf=${conf_path}" ;;
         esac
         ;;
       :)
@@ -240,30 +207,29 @@ start_es() {
 
   local cmd="${ES_CMD}"
   if [[ ! -z "${cmd_opts}" ]]; then
-    cmd="${cmd} "${cmd_opts}""
+    cmd="${cmd} ${cmd_opts}"
   fi
 
-  echo "Starting Elasticsearch ${current_version}, please wait..."
+  echo "==> Starting Elasticsearch ${current_version}"
   ${cmd}
   _wait_for_es_started_completely
 }
 
 stop_es() {
-  local pid=$(_get_current_es_pid)
+  echo "==> Stopping Elasticsearch"
+  local pid="$(_get_current_es_pid)"
   if [[ -z "${pid}" ]]; then
     _abort "Elasticsearch is not running."
   fi
   kill -SIGTERM "${pid}" || _abort "Could not stop Elasticsearch."
-  local current_version="$(_get_current_es_version)"
-  echo "Elasticsearch ${current_version} has been stopped."
+  echo "Elasticsearch $(_get_current_es_version) has been stopped."
 }
 
 
 print_es_running_status() {
-  local pid=$(_get_current_es_pid)
+  local pid="$(_get_current_es_pid)"
   if [[ ! -z "${pid}" ]]; then
-    local current_version="$(_get_current_es_version)"
-    echo "Elasticsearch ${current_version} is running."
+    echo "Elasticsearch $(_get_current_es_version) is running."
   else
     echo "Elasticsearch is not running."
   fi
@@ -287,7 +253,7 @@ remove_es() {
   fi
 
   rm -rf "${removed_version_folder}" || _abort "Could not remove the version ${version}."
-  echo "-> Elasticsearch ${version} has been removed"
+  echo "Elasticsearch ${version} has been removed."
 }
 
 manage_es_plugin() {
@@ -346,11 +312,11 @@ manage_es_plugin() {
   ${cmd}
 }
 
-list_all_es_versions() {
-  local current_version=$(_get_current_es_version)
+list_es_versions() {
+  local current_version="$(_get_current_es_version)"
   for e in $(find "${EVM_HOME}" -maxdepth 1 -mindepth 1 -type d -name "${ES_NAME}-*" | sort -nr); do
     local version="$(basename "${e}")"
-    version="$(echo ${version} | cut -d "-" -f 2)"
+    version="$(echo "${version}" | cut -d "-" -f 2)"
     if [[ "${current_version}" = "${version}" ]]; then
       echo -e "\033[0;32m* ${version}\033[0m"
     else
@@ -364,11 +330,11 @@ print_evm_version(){
 }
 
 print_current_es_version() {
-  echo "$(_get_current_es_version)"
+  _get_current_es_version
 }
 
 print_es_path(){
-  local version="${1:-$(_get_current_version)}"
+  local version="${1:-$(_get_current_es_version)}"
   _check_es_version "${version}"
 
   local path="$ES_HOME-$version"
@@ -441,7 +407,7 @@ main() {
     ${WHICH_CMD}) print_es_path "$@" ;;
     ${LIST_CMD})
       _abort_if_too_many_arguments "$@"
-      list_all_es_versions
+      list_es_versions
       ;;
     ${VERSION_CMD})
       _abort_if_too_many_arguments "$@"
