fix errors reported by shellcheck

diff --git a/evm b/evm
--- a/evm
+++ b/evm
@@ -6,18 +6,17 @@ SCRIPT="$0"
 
 # SCRIPT may be an arbitrarily deep series of symlinks. Loop until we have the concrete path.
 while [ -h "$SCRIPT" ] ; do
-  ls=`ls -ld "$SCRIPT"`
+  ls=$(ls -ld "$SCRIPT")
   # Drop everything prior to ->
-  link=`expr "$ls" : '.*-> \(.*\)$'`
+  link=$(expr "$ls" : '.*-> \(.*\)$')
   if expr "$link" : '/.*' > /dev/null; then
     SCRIPT="$link"
   else
-    SCRIPT=`dirname "$SCRIPT"`/"$link"
+    SCRIPT=$(dirname "$SCRIPT")/"$link"
   fi
 done
 
-EVM_NAME=$(basename $SCRIPT)
-EVM_VERSION='0.1.0'
+EVM_NAME=$(basename "$SCRIPT")
 EVM_HOME=${EVM_HOME:-"$HOME/.$EVM_NAME"}
 
 ES="elasticsearch"
@@ -29,13 +28,13 @@ ES_5X_DOWNLOAD_REPO="https://artifacts.elastic.co/downloads/elasticsearch"
 ES_DOWNLOAD_EXT='tar.gz'
 
 # First use?
-if [ ! -d $EVM_HOME ]; then
-  mkdir -p $EVM_HOME;
+if [ ! -d "$EVM_HOME" ]; then
+  mkdir -p "$EVM_HOME";
 fi
 
 
 abort(){
-  echo ${1:-"Abort!"}; exit 3
+  echo "${1:-"Abort!"}"; exit 3
 }
 
 _get_es_download_link() {
@@ -56,13 +55,13 @@ _get_es_download_link() {
 
 
 install_es_version() {
-  version=$1
+  version="$1"
 
   if [ -d "$ES_HOME-$version" ]; then
     abort "Elasticsearch $version has been already installed."
   fi
 
-  download_link=$(_get_es_download_link $version)
+  download_link="$(_get_es_download_link "$version")"
   if [ "x$download_link" = "x" ]; then
     abort "Unknown Elasticsearch version $version"
   fi
@@ -70,56 +69,56 @@ install_es_version() {
   echo "-> Dowloading Elasticsearch $version from elastic.co"
   echo "Retrieving $download_link"
   output_file="$EVM_HOME/$ES-$version.$ES_DOWNLOAD_EXT"
-  wget -nc $download_link -O $output_file
+  wget -nc "$download_link" -O "$output_file"
   echo "Installing $output_file"
-  tar -xzf $output_file -C "$EVM_HOME/"
+  tar -xzf "$output_file" -C "$EVM_HOME/"
   echo "-> Installed elasticsearch $version."
   if [ ! -f "$ES_HOME/bin/elasticsearch" ]; then
-    use_es_version $version
+    use_es_version "$version"
   fi
-  rm -rf $output_file
+  rm -rf "$output_file"
 }
 
 use_es_version() {
-  version=$1
+  version="$1"
   use_version="$ES_HOME-$version"
-  if [ ! -d $use_version ]; then
+  if [ ! -d "$use_version" ]; then
     abort "The version $version has not installed yet."
   fi
-  ln -sfn $use_version $ES_HOME
+  ln -sfn "$use_version" "$ES_HOME"
   echo "-> Now using Elasticsearch $version."
 }
 
 start_es() {
   cmd="$ES_HOME/bin/elasticsearch"
-  if [ ! -x $cmd ]; then
+  if [ ! -x "$cmd" ]; then
     abort "Elasticsearch has not been installed yet."
   fi
   option_config_path="$1"
   if [ "$option_config_path" = "--config-path" ]; then
     config_path="$2"
-    if [ ! -d $config_path ]; then
-      abort "The config path '$config' does not exist or cannot access."
+    if [ ! -d "$config_path" ]; then
+      abort "The config path '$config_path' does not exist or cannot access."
     fi
-    cmd="$cmd -Epath.conf=$config"
+    cmd="$cmd -Epath.conf=$config_path"
   fi
   $cmd
 }
 
 remove_es_version() {
-  version=$1
+  version="$1"
   uninstall_version="$ES_HOME-$version"
 
   if [ ! -d "$uninstall_version" ]; then
     abort "The Elasticsearch $version has not been installed yet."
   fi
 
-  current_version=`readlink "$ES_HOME"`
+  current_version="$(readlink "$ES_HOME")"
   if [ "$uninstall_version" = "$current_version" ]; then
     abort "The Elasticsearch $version is in use."
   fi
-  rm -rf $uninstall_version
-  echo "-> The Elasticsearch $version has been uninstalled."
+  rm -rf "$uninstall_version"
+  echo "-> The Elasticsearch $version has been removed."
 }
 
 manage_es_plugin() {
@@ -128,10 +127,10 @@ manage_es_plugin() {
   fi
   # 5.x?
   cmd="$ES_HOME/bin/elasticsearch-plugin"
-  if [ ! -f $cmd ]; then
+  if [ ! -f "$cmd" ]; then
     # No? Try 1.x or 2.x...
     cmd="$ES_HOME/bin/plugin"
-    if [ ! -f $cmd ]; then
+    if [ ! -f "$cmd" ]; then
       # No?
       abort "Plugin command not found."
     fi
@@ -156,19 +155,19 @@ manage_es_plugin() {
   $cmd
 }
 
-_find_current_es_version() {
-  for e in $(ls -d $EVM_HOME/*); do
-    echo $(readlink $e)
-  done
+get_current_es_version() {
+  current_version="$(basename "$(find "$EVM_HOME" -type l -name "$ES" -exec readlink {} +)")"
+  printf "%s\n" "$current_version"
 }
 
 list_es_versions() {
-  current_version=$(_find_current_es_version)
-  for e in $(ls -d $EVM_HOME/* | grep "$ES-" | sort -nr); do
+  current_version=$(get_current_es_version)
+  for e in $(find "$EVM_HOME" -type d -name "$ES-*" -maxdepth 1 -mindepth 1 | sort -nr); do
+    e="$(basename "$e")"
     if [ "$current_version" = "$e" ]; then
-      printf "%-2s %s\n" "*" "$(basename $e) (in use)"
+      printf "%-2s %s\n" "*" "$e (in use)"
     else
-      printf "%-2s %s\n" "" "$(basename $e)"
+      printf "%-2s %s\n" "" "$e"
     fi
   done
 }
@@ -193,35 +192,38 @@ usage() {
   printf " %-50s %s\n" "$EVM_NAME start --config-path /etc/elasticsearch" "Start Elasticsearch node with /etc/elasticsearch config directory"
   printf " %-50s %s\n" "$EVM_NAME plugin --install x-pack" "Install the x-pack plugin"
   printf " %-50s %s\n" "$EVM_NAME plugin --remove x-pack" "Remove the x-pack plugin"
-  printf '\nNote: To remove, delete or uninstall evm - just remove the $EVM_HOME folder (usually ~/.evm)\n'
+  printf "\nNote: To remove, delete or uninstall evm - just remove the EVM_HOME folder (usually ~/.evm)\n"
   printf "\n"
   exit 3
 }
 
 cmd="$1"
-case $cmd in
+case "$cmd" in
     install)
       version="$2"
-      install_es_version $version
+      install_es_version "$version"
       ;;
     use)
       version="$2"
-      use_es_version $version
+      use_es_version "$version"
       ;;
     start)
       start_es "$2" "$3"
       ;;
     remove)
       version="$2"
-      remove_es_version $version
+      remove_es_version "$version"
       ;;
     plugin)
       option="$2"
       plugin="$3"
-      manage_es_plugin $option $plugin
+      manage_es_plugin "$option" "$plugin"
       ;;
     list)
       list_es_versions
+      ;;
+    which)
+      get_current_es_version
       ;;
     help|-h|--help)
       usage
