1)Add which <version> command 2) Validate commands  options & agruments 3) Refactoring

diff --git a/evm b/evm
--- a/evm
+++ b/evm
@@ -1,61 +1,67 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # Elasticsearch Version Manager
 # Purpose: Managing multiple Elasticsearch versions on your local development machine
 # Licence: Apache License, version 2 (http://www.apache.org/licenses/LICENSE-2.0)
 # Source: https://github.com/duydo/evm
-# Version: 0.1.3
+# Version: 0.1.4
 # Author: Duy Do (duydo)
 # Contributors: Quang Nguyen (xluffy), Nham Le (nhamlh)
-EVM_VERSION="0.1.3"
+
+readonly EVM_VERSION="0.1.4"
 
 SCRIPT="$0"
 # SCRIPT may be an arbitrarily deep series of symlinks, lookup the concrete path.
 if [[ -h "${SCRIPT}" ]]; then
-  SCRIPT=$(readlink "${SCRIPT}")
+  SCRIPT="$(readlink "${SCRIPT}")"
 fi
 
-EVM_NAME=$(basename "${SCRIPT}")
-EVM_HOME=${EVM_HOME:-"${HOME}/.${EVM_NAME}"}
+readonly EVM_NAME=$(basename "${SCRIPT}")
+readonly EVM_HOME=${EVM_HOME:-"${HOME}/.${EVM_NAME}"}
 
-ES="elasticsearch"
-ES_HOME="${EVM_HOME}/${ES}"
-ES_CMD="${ES_HOME}/bin/${ES}"
-ES_PLUGIN_CMD="${ES_HOME}/bin/${ES}-plugin"
-ES_1X_PLUGIN_CMD="${ES_HOME}/bin/plugin"
+readonly ES="elasticsearch"
+readonly ES_HOME="${EVM_HOME}/${ES}"
+readonly ES_CMD="${ES_HOME}/bin/${ES}"
+readonly ES_PLUGIN_CMD="${ES_HOME}/bin/${ES}-plugin"
+readonly ES_1X_PLUGIN_CMD="${ES_HOME}/bin/plugin"
 
 # Sub commands
-START_CMD='start'
-INSTALL_CMD='install'
-REMOVE_CMD='remove'
-LIST_CMD='list'
-USE_CMD='use'
-PLUGIN_CMD='plugin'
-VERSION_CMD='version'
-WHICH_CMD='which'
+readonly START_CMD='start'
+readonly INSTALL_CMD='install'
+readonly REMOVE_CMD='remove'
+readonly LIST_CMD='list'
+readonly USE_CMD='use'
+readonly PLUGIN_CMD='plugin'
+readonly VERSION_CMD='version'
+readonly WHICH_CMD='which'
 
 # Elasticsearch download repos
-ES_1X_DOWNLOAD_REPO="https://download.elastic.co/elasticsearch/elasticsearch"
-ES_2X_DOWNLOAD_REPO="https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch"
-ES_5X_DOWNLOAD_REPO="https://artifacts.elastic.co/downloads/elasticsearch"
-ES_DOWNLOAD_EXT="tar.gz"
+readonly ES_1X_DOWNLOAD_REPO="https://download.elastic.co/elasticsearch/elasticsearch"
+readonly ES_2X_DOWNLOAD_REPO="https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch"
+readonly ES_5X_DOWNLOAD_REPO="https://artifacts.elastic.co/downloads/elasticsearch"
+readonly ES_DOWNLOAD_EXT="tar.gz"
 
 # First use?
-if [ ! -d "${EVM_HOME}" ]; then
+if [[ ! -d "${EVM_HOME}" ]]; then
   mkdir -p "${EVM_HOME}";
 fi
 
+_abort(){
+  echo "${1:-"Something went wrong! Use evm -h for help."}"; exit 1
+}
 
-abort(){
-  echo "${1:-"Something went wrong. Use evm -h for help."}"; exit 1
+_abort_if_too_many_arguments() {
+  if [[ ! -z "$@" ]]; then
+    _abort "Too many arguments. Use evm -h for help."
+  fi
 }
 
 _check_version() {
   local version="$1"
   if [[ -z "${version}" ]]; then
-    abort "A version is required."
+    _abort "A version is required."
   elif [[ ! "${version}" =~ ^([0-9]+\.){2}(\*|[0-9]+)$ ]]; then
-    abort "Invalid version: '${version}'."
+    _abort "Invalid version: '${version}'."
   fi
 }
 
@@ -82,165 +88,205 @@ _get_download_link() {
   fi
 }
 
-get_current_version() {
+_get_current_version() {
   local current_version="$(basename "$(find "${EVM_HOME}" -type l -name "${ES}" -exec readlink {} +)")"
   echo "${current_version}" | cut -d "-" -f 2
 }
 
 install_version() {
-
-  local version="$1"
+  local version="$1"; shift
+  _abort_if_too_many_arguments "$@"
   _check_version "${version}"
-
   if [[ -d "${ES_HOME}-${version}" ]]; then
-    abort "Elasticsearch ${version} has been already installed."
+    _abort "Elasticsearch ${version} has been already installed."
   fi
 
   local download_link="$(_get_download_link "${version}")"
   if [[ -z "${download_link}" ]]; then
-    abort "Elasticsearch ${version} not found."
+    _abort "Elasticsearch ${version} not found."
   fi
 
   echo "-> Downloading Elasticsearch ${version} from elastic.co"
   echo "Retrieving ${download_link}"
   local output_file="${EVM_HOME}/${ES}-${version}.${ES_DOWNLOAD_EXT}"
-  wget -nc "${download_link}" -O "${output_file}"
-
+  wget -c "${download_link}" -O "${output_file}" || _abort "Could not download ${output_file}!"
   # TODO: Verify downloaded file's checksum before installing (suggested by @xluffy)
 
   echo "Installing ${output_file}"
-  tar -xzf "${output_file}" -C "${EVM_HOME}/"
-
-  # Use this version if no other version in use
-  local current_version=$(get_current_version)
-  if [ -z "${current_version}" ]; then
-    use_version "${version}"
-  fi
+  tar -xzf "${output_file}" -C "${EVM_HOME}/" || _abort "Could not extract the ${output_file}, please try to install again."
 
   # Remove the downloaded file
-  if rm -rf "${output_file}"; then
-    echo "Removed ${output_file}"
-  fi
-
+  rm -rf "${output_file}" || echo "Clean failed. Could not remove the downloaded file ${output_file}!"
   echo "-> Installed Elasticsearch ${version}"
+
+  # Use this version if no other version in use
+  local current_version=$(_get_current_version)
+  if [[ -z "${current_version}" ]]; then
+    use_version "${version}"
+  fi
 }
 
 use_version() {
-  local version="$1"
+  local version="$1"; shift
+  _abort_if_too_many_arguments "$@"
   _check_version "${version}"
+
   local use_version="${ES_HOME}-${version}"
   if [[ ! -d "${use_version}" ]]; then
-    abort "Elasticsearch ${version} not found. Use 'evm list' to see available versions."
+    _abort "Elasticsearch ${version} not found."
   fi
-  if ln -sfn "${use_version}" "${ES_HOME}"; then
-    echo "-> Now using Elasticsearch ${version}"
-  else
-    abort
-  fi
+
+  ln -sfn "${use_version}" "${ES_HOME}" || _abort "Could not create symbolic link ${ES_HOME} => ${use_version}"
+  echo "-> Now using Elasticsearch ${version}"
 }
 
 start_current_version() {
-	local cmd="${ES_CMD}"
-  if [[ ! -x "${cmd}" ]]; then
-    abort "The command ${cmd} is not executable, no Elasticsearch version in use."
+  local current_version="$(_get_current_version)"
+	if [[ -z "${current_version}" ]]; then
+    _abort "No Elasticsearch version in use."
   fi
+
+  local cmd_opts
 	while getopts ":c:" option; do
     case "${option}" in
       c)
-        local config_path="$OPTARG"
-        if [[ ! -d "${config_path}" ]]; then
-          abort "Invalid config path: '${config_path}'"
+        local conf_path="$OPTARG"
+        if [[ ! -d "${conf_path}" ]]; then
+          _abort "Invalid config path: '${conf_path}'"
         fi
-        local current_version="$(get_current_version)"
-				case "$current_version" in
-				  1.*|2.*) cmd="${cmd} -Des.path.conf=${config_path}" ;;
-          *) cmd="${cmd} -Epath.conf=${config_path}" ;;
+  			case "$current_version" in
+  			  1.*|2.*)
+  				  cmd_opts="-Des.path.conf=${conf_path}"
+  				  ;;
+          *)
+            cmd_opts="-Epath.conf=${conf_path}"
+            ;;
         esac
+        ;;
+      :)
+        _abort "The option [-$OPTARG] must not be empty." ;;
+      \?)
+        _abort "Unknown option: [-$OPTARG]. Use evm -h for help." ;;
     esac
 	done
+	shift "$((OPTIND -1))"
+
+	_abort_if_too_many_arguments "$@"
+
+	local cmd="${ES_CMD}"
+	if [[ ! -z "${cmd_opts}" ]]; then
+	  cmd="${cmd} "${cmd_opts}""
+	fi
 	${cmd}
 }
 
 remove_version() {
-  local version="$1"
+  local version="$1"; shift
+  _abort_if_too_many_arguments "$@"
   _check_version "${version}"
 
-  local removed_version_folder="${ES}-${version}"
-  if [[ ! -d "${EVM_HOME}/${removed_version_folder}" ]]; then
-    abort "Elasticsearch ${version} not found."
+  local removed_version_folder="${ES_HOME}-${version}"
+  if [[ ! -d "${removed_version_folder}" ]]; then
+    _abort "Elasticsearch ${version} not found."
   fi
 
-  local current_version="$(get_current_version)"
+  local current_version="$(_get_current_version)"
   if [[ "${version}" = "${current_version}" ]]; then
-    abort "Elasticsearch ${version} is in use."
+    _abort "Could not remove Elasticsearch ${version}, it is in use."
   fi
 
-  if rm -rf "${EVM_HOME}/${removed_version_folder}"; then
-    abort "Could not remove the version ${version}."
-  else
-    echo "-> Elasticsearch ${version} has been removed"
-  fi
+  rm -rf "${removed_version_folder}" || _abort "Could not remove the version ${version}."
+  echo "-> Elasticsearch ${version} has been removed"
 }
 
 manage_plugin() {
-
-  list_option="list"
-  install_option="install"
-  remove_option="remove"
-
-  local current_version="$(get_current_version)"
-  case "${current_version}" in
-    '')
-      abort "No Elasticsearch version in use. Use evm -h for help."
-      ;;
-    1.*)
-      cmd="${ES_HOME}/bin/plugin"
-      list_option="--list"
-      install_option="--install"
-      remove_option="--remove"
-      ;;
-    2.*)
-      cmd="${ES_HOME}/bin/plugin"
-      ;;
-    *)
-      cmd="${ES_HOME}/bin/elasticsearch-plugin"
-      ;;
-  esac
-
-  if [ ! -x "$cmd" ]; then
-    abort "The Elasticsearch plugin command not found or unexecutable."
+  local current_version="$(_get_current_version)"
+  if [[ -z "${current_version}" ]]; then
+    _abort "No Elasticsearch version in use. Use evm -h for help."
   fi
 
-  plugin_sub_cmd="$1"
-  shift
-  case "$plugin_sub_cmd" in
-    list)
-      cmd="$cmd $list_option"
+  local list_opt="${LIST_CMD}"
+  local install_opt="${INSTALL_CMD}"
+  local remove_opt="${REMOVE_CMD}"
+  case "${current_version}" in
+    1.*)
+      cmd="${ES_1X_PLUGIN_CMD}"
+      list_opt="--${list_opt}"
+      install_opt="--${install_opt}"
+      remove_opt="--${remove_opt}"
       ;;
-    install)
-      cmd="$cmd $install_option $@"
-      ;;
-    remove)
-      cmd="$cmd $remove_option $@"
+    2.*)
+      cmd="${ES_1X_PLUGIN_CMD}"
       ;;
     *)
-      abort "The command 'plugin' requires a valid argument. Use evm -h for help."
+      cmd="${ES_PLUGIN_CMD}"
+      ;;
+  esac
+  if [ ! -x "$cmd" ]; then
+    _abort "The Elasticsearch plugin command not found or unexecutable."
+  fi
+
+  local plugin_sub_cmd="$1"; shift
+  case "$plugin_sub_cmd" in
+    ${LIST_CMD})
+      _abort_if_too_many_arguments "$@"
+      cmd="$cmd $list_opt"
+      ;;
+    ${INSTALL_CMD})
+      local plugin="$1"; shift
+      _abort_if_too_many_arguments "$@"
+      if [[ -z "${plugin}" ]]; then
+        _abort "A plugin is required."
+      fi
+      cmd="$cmd $install_opt ${plugin}"
+      ;;
+    ${REMOVE_CMD})
+      local plugin="$1"; shift
+      _abort_if_too_many_arguments "$@"
+      if [[ -z "${plugin}" ]]; then
+        _abort "A plugin is required."
+      fi
+      cmd="$cmd $remove_opt ${plugin}"
+      ;;
+    *)
+      _abort "Unknown command: '${plugin_sub_cmd}'. Use evm -h for help."
     ;;
   esac
+
   ${cmd}
 }
 
 list_versions() {
-  local current_version=$(get_current_version)
-  for e in $(find "$EVM_HOME" -maxdepth 1 -mindepth 1 -type d -name "$ES-*" | sort -nr); do
-    version="$(basename "$e")"
-    version="$(echo $version | cut -d "-" -f 2)"
-    if [[ "$current_version" = "$version" ]]; then
-      echo -e "\033[0;32m* $version\033[0m"
+  local current_version=$(_get_current_version)
+  for e in $(find "${EVM_HOME}" -maxdepth 1 -mindepth 1 -type d -name "${ES}-*" | sort -nr); do
+    local version="$(basename "${e}")"
+    version="$(echo ${version} | cut -d "-" -f 2)"
+    if [[ "${current_version}" = "${version}" ]]; then
+      echo -e "\033[0;32m* ${version}\033[0m"
     else
-      echo -e "  $version"
+      echo -e "  ${version}"
     fi
   done
+}
+
+print_evm_version(){
+  echo "${EVM_NAME} ${EVM_VERSION}"
+}
+
+print_current_version() {
+  echo "$(_get_current_version)"
+}
+
+print_version_path(){
+  local version="${1:-$(_get_current_version)}"
+  _check_version "${version}"
+
+  local path="$ES_HOME-$version"
+  if [[ -d "${path}" ]]; then
+    echo "${path}"
+  else
+    echo "Elasticsearch ${version} not found."
+  fi
 }
 
 print_usage() {
@@ -249,47 +295,29 @@ print_usage() {
 Elasticsearch Version Manager
 
 Usage:
- evm -h                                             Print help information
- evm -V                                             Print version information
- evm list                                           List all installed Elasticsearch versions
- evm version                                        Print the current activated Elasticsearch version
- evm install <version>                              Install a specific Elasticsearch version
- evm use <version>                                  Use a specific Elasticsearch version
- evm remove <version>                               Remove a specific Elasticsearch version if available
- evm which [<version>]                              Print path to installed Elasticsearch version
- evm plugin list                                    List all installed Elasticsearch plugins
- evm plugin <install|remove> <plugin>               Install or remove an Elasticsearch plugin
- evm start [-c </path/to/config/dir>]               Start Elasticsearch with/without a specific config directory
+ evm -h                                   Print help information
+ evm -V                                   Print version information
+ evm list                                 List all installed Elasticsearch versions
+ evm version                              Print the current activated Elasticsearch version
+ evm install <version>                    Install a specific Elasticsearch version
+ evm use <version>                        Use a specific Elasticsearch version
+ evm remove <version>                     Remove a specific Elasticsearch version if available
+ evm which [<version>]                    Print path to installed Elasticsearch version
+ evm plugin list                          List all installed Elasticsearch plugins
+ evm plugin <install|remove> <plugin>     Install or remove an Elasticsearch plugin
+ evm start [-c </path/to/config/dir>]     Start Elasticsearch with/without a specific config directory
 
 Example:
- evm install 5.3.1                                  Install Elasticsearch 5.3.1
- evm use 5.3.1                                      Use Elasticsearch 5.3.1
- evm start                                          Start Elasticsearch node with the default config directory
- evm start -c /etc/elasticsearch                    Start Elasticsearch node with /etc/elasticsearch config directory
- evm plugin install x-pack                          Install the x-pack plugin
- evm plugin remove x-pack                           Remove the x-pack plugin
+ evm install 5.3.1                        Install Elasticsearch 5.3.1
+ evm use 5.3.1                            Use Elasticsearch 5.3.1
+ evm start                                Start Elasticsearch node with the default config directory
+ evm start -c /etc/elasticsearch          Start Elasticsearch node with /etc/elasticsearch config directory
+ evm plugin install x-pack                Install the x-pack plugin
+ evm plugin remove x-pack                 Remove the x-pack plugin
 
-Note: To remove evm - just remove the EVM_HOME folder (usually ~/.evm)
+Note: To uninstall, just remove the $EVM_HOME folder (usually ~/.evm)
 
 EOF
-}
-
-print_evm_version(){
-  echo "$EVM_NAME $EVM_VERSION"
-}
-
-print_current_version() {
-  echo "$(get_current_version)"
-}
-
-print_version_path(){
-  local version="${1:-$(get_current_version)}"
-  local path="$EVM_HOME/$ES-$version"
-  if [[ -d "${path}" ]]; then
-    echo "${path}"
-  else
-    echo "Elasticsearch version not found."
-  fi
 }
 
 main() {
@@ -297,11 +325,10 @@ main() {
     case "${opt}" in
       h) print_usage; exit 0 ;;
       V) print_evm_version; exit 0 ;;
-      \?) abort "Unknown option: -${OPTARG}. Use evm -h for help." ;;
+      \?) _abort "Unknown option: -${OPTARG}. Use evm -h for help." ;;
     esac
   done
   shift "$((OPTIND -1))"
-
   sub_cmd="$1"; shift
   case "${sub_cmd}" in
     ${INSTALL_CMD}) install_version "$@" ;;
@@ -310,13 +337,17 @@ main() {
     ${REMOVE_CMD}) remove_version "$@" ;;
     ${PLUGIN_CMD}) manage_plugin "$@" ;;
     ${WHICH_CMD}) print_version_path "$@" ;;
-    ${LIST_CMD}) list_versions ;;
-    ${VERSION_CMD}) print_current_version ;;
-    *) abort "Invalid command: '${sub_cmd}'. Use evm -h for help." ;;
+    ${LIST_CMD})
+      _abort_if_too_many_arguments "$@"
+      list_versions
+      ;;
+    ${VERSION_CMD})
+      _abort_if_too_many_arguments "$@"
+      print_current_version
+      ;;
+    *) print_usage ;;
   esac
-
 }
 
 main "$@"
-
 exit $?
